import Head from "next/head";
import styles from "../styles/main-background-image.module.css";


export default function Home()
{
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center bg-slate-200 overflow-hidden">
        <div className={`h-full w-full ${styles.mainBackgroundImage}`}>
          <div className="flex flex-row justify-center py-80">
            <div className="flex flex-col justify-center py-80">
              <h3 className="text-slate-100 center ">
                Marcelo<br />Firpo
              </h3>
              <p>
                ajbkjrkjbs
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
