import Head from "next/head";
import { PropsWithChildren } from "react";
import { BottomBar } from "../components/bottomBar";
import { ExpositionText } from "../components/expositionText";
import { Hero } from "../components/hero";
import { PieceCollection } from "../components/pieceCollection";

function HorizontalCenter(props: PropsWithChildren)
{
    return <div className="w-screen flex justify-center">
        {props.children}
    </div>;
}

const Home = () => (
    <>
        <Head>
            <title>Marcelo Firpo</title>
            <meta name="description" content="Generated by create-t3-app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="bg-white flex flex-col justify-center">
            <Hero/>
            <ExpositionText/>
            <HorizontalCenter>
                <PieceCollection/>
            </HorizontalCenter>
            <BottomBar/>
        </main>
    </>
);

export default Home
