import Head from "next/head";
import { BottomBar } from "../components/bottomBar";
import { ExpositionText } from "../components/expositionText";
import { Hero } from "../components/hero";
import { PieceCollection } from "../components/pieceCollection";
import { HorizontalCenter } from "../components/horizontalCenter";

const Home = () => (
    <>
        <Head>
            <title>Marcelo Firpo</title>
            <meta name="description" content="Generated by create-t3-app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="bg-white flex flex-col justify-center overflow-hidden">
            <Hero/>
            <ExpositionText/>
            <div className="pt-[285px]">
                <HorizontalCenter>
                    <PieceCollection/>
                </HorizontalCenter>
            </div>
            <div className="p-[88px]">
                <HorizontalCenter>
                    <BottomBar/>
                </HorizontalCenter>
            </div>
        </main>
    </>
);

export default Home
